# Generated by Django 6.0 on 2026-01-19 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('mobile_number', models.CharField(max_length=10)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=100)),
                ('department', models.CharField(choices=[('IT', 'IT'), ('CSE', 'CSE'), ('ECE', 'ECE'), ('EEE', 'EEE'), ('MECH', 'MECH')], max_length=10)),
                ('year_of_study', models.CharField(choices=[('1st', '1st'), ('2nd', '2nd'), ('3rd', '3rd'), ('4th', '4th')], max_length=10)),
                ('roll_number', models.CharField(max_length=10, unique=True)),
                ('address', models.TextField()),
                ('state', models.CharField(choices=[('Andhra Pradesh', 'Andhra Pradesh'), ('Telangana', 'Telangana'), ('Karnataka', 'Karnataka'), ('Tamil Nadu', 'Tamil Nadu')], max_length=20)),
                ('pincode', models.CharField(max_length=6)),
                ('technical_skills', models.CharField(max_length=100)),
                ('learning_mode', models.CharField(choices=[('Online', 'Online'), ('Offline', 'Offline'), ('Hybrid', 'Hybrid')], max_length=10)),
                ('resume', models.FileField(upload_to='resumes/')),
                ('about_yourself', models.TextField()),
                ('agree_to_terms', models.BooleanField()),
            ],
        ),
    ]
